version: '3'

services:
  # Next.js Application (f端r Nginx Proxy Manager)
  realtime-app:
    build:
      context: .
      dockerfile: Dockerfile
    # Port f端r direkten Zugriff und Nginx Proxy Manager
    ports:
      - "3000:3000"  # Direkter Zugriff f端r Development/Testing
    expose:
      - "3000"  # F端r Nginx Proxy Manager
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - PORT=3000
    networks:
      - realtime-network
      - nginx-rp-manager_default  # Verbindung zum Nginx Proxy Manager Netzwerk
    restart: unless-stopped
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 40s

  # Redis for Session Management (Optional)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - realtime-network
    restart: unless-stopped
    command: redis-server --appendonly yes

networks:
  realtime-network:
    driver: bridge
  nginx-rp-manager_default:
    external: true

volumes:
  redis-data:
    driver: local
