version: '3'

services:
  # Next.js Application (direkt exposed für deinen Nginx)
  realtime-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Next.js App mit Socket.IO
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - PORT=3000
    networks:
      - realtime-network
    restart: unless-stopped
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 40s

  # Redis for Session Management (Optional)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - realtime-network
    restart: unless-stopped
    command: redis-server --appendonly yes

networks:
  realtime-network:
    driver: bridge

volumes:
  redis-data:
    driver: local
