import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import { DeviceProvider } from "@/contexts/DeviceContext";
import { SocketProvider } from "@/contexts/SocketContext";
import GhostUser from "@/lib/ghostUser";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // GhostUser beim App-Start verbinden (nur Client)
  if (typeof window !== 'undefined') {
    GhostUser.connectToRooms(['lobby']);
  }
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SocketProvider>
          <DeviceProvider>
            {children}
          </DeviceProvider>
        </SocketProvider>
      </body>
    </html>
  );
}
